export const config = {
  default: {
    country: "Pakistan",
    city: "Rawalpindi",
    method: "1",
    school: "0",
    latitudeAdjustment: "Middle of the Night Method",
    midnightCalculation: "Standard (Mid Sunset to Sunrise)",
  },
  schools: ["Shafi", "Hanafi"],
  methods: [
    "Shia Ithna-Ansari",
    "University of Islamic Sciences, Karachi",
    "Islamic Society of North America",
    "Muslim World League",
    "Umm al-Qura University, Makkah",
    "Egyptian General Authority of Survey",
    "Institute of Geophysics, University of Tehran",
    "Gulf Region",
    "Kuwait",
    "Qatar",
    "Majlis Ugama Islam Singapura, Singapore",
    "Union Organization islamic de France",
    "Diyanet İşleri Başkanlığı, Turkey",
    "Spiritual Administration of Muslims of Russia",
    "Ministry of Awqaf and Islamic Affairs, Kuwait",
    "Ministry of Religious Affairs and Wakfs, Algeria",
    "Ministry of Religious Affairs, Tunisia",
    "Ministry of Endowments and Islamic Affairs, Qatar",
  ],
  lattitude_adjustment_options: [
    "Middle of the Night Method",
    "One Seventh Rule",
    "Angle Based Method",
  ],
  mindnight_calculation_options: [
    "Standard (Mid Sunset to Sunrise)",
    "Jafari (Mid Sunset to Fajr)",
  ],
};
